on:
  push:
    paths: "project/**"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: dbt-mermaid
        uses: "./" # kitta65/dbt-mermaid@vX.X.X
        with:
          dbt-version: 1.7.11
          dbt-project: project
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.dbt-mermaid.outputs.filepath }}
